# Generated by Django 3.2.9 on 2021-12-25 12:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_user', '0009_auto_20211225_0408'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryListOtherUserConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('other_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referral.otheruser')),
                ('secondary_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referral.secondarylist')),
            ],
        ),
        migrations.AddField(
            model_name='secondarylist',
            name='other_users',
            field=models.ManyToManyField(through='referral.SecondaryListOtherUserConnector', to='referral.OtherUser'),
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_user_id', models.CharField(default='none', max_length=500)),
                ('amount', models.FloatField(default=0)),
                ('request_status', models.BooleanField(default=False)),
                ('paid_status', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryListOtherUserConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('other_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referral.otheruser')),
                ('primary_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referral.primarylist')),
            ],
        ),
        migrations.AddField(
            model_name='primarylist',
            name='other_users',
            field=models.ManyToManyField(through='referral.PrimaryListOtherUserConnector', to='referral.OtherUser'),
        ),
    ]
